### ISSUE TITLE
[Meta issue] List of failing/empty/flaky tests

### ISSUE THREAD

**Issue by 0xMimir** [openmina/openmina#524]
# Failing tests:

Scenario:
- [x] [`run_ocaml`](https://github.com/openmina/openmina/blob/develop/node/testing/src/node/ocaml/mod.rs?plain=0#L447)
  - Fixed by https://github.com/openmina/openmina/pull/592
- [x] [`rust_to_ocaml`](https://github.com/openmina/openmina/blob/develop/node/testing/tests/connection_discovery.rs)
  - Fixed by https://github.com/openmina/openmina/pull/578
- [x] [`ocaml_to_rust`](https://github.com/openmina/openmina/blob/develop/node/testing/tests/connection_discovery.rs)
  - Fixed by https://github.com/openmina/openmina/pull/578
- [x] [`rust_to_ocaml_via_seed`](https://github.com/openmina/openmina/blob/develop/node/testing/tests/connection_discovery.rs)
  - Fixed by https://github.com/openmina/openmina/pull/578
- [x] [`ocaml_to_rust_via_seed`](https://github.com/openmina/openmina/blob/develop/node/testing/tests/connection_discovery.rs)
  - FIxed by https://github.com/openmina/openmina/pull/578
- [x] [`rust_as_seed`](https://github.com/openmina/openmina/blob/develop/node/testing/tests/connection_discovery.rs)
  - Fixed by https://github.com/openmina/openmina/pull/578
- [ ] [`block`](https://github.com/openmina/openmina/blob/develop/p2p/tests/rpc.rs#141)
- [ ] [`staged_ledger_aux_and_pending_coinbases_at_block`](https://github.com/openmina/openmina/blob/develop/p2p/tests/rpc.rs#147)

These tests need to be rewritten:
- [x] [`incoming_find_node`](https://github.com/openmina/openmina/blob/develop/node/testing/tests/p2p_kad.rs)
  - Fxied by https://github.com/openmina/openmina/pull/578
- [x] [`kademlia_bootstrap`](https://github.com/openmina/openmina/blob/develop/node/testing/tests/p2p_kad.rs)
  - Fixed by https://github.com/openmina/openmina/pull/578

Ignored:
- [x] [`binable_base58check`](https://github.com/openmina/openmina/blob/develop/mina-p2p-messages/src/b58.rs#L380)
- [ ] `test_payment_hash_1`
- [ ] [`state_hash`](https://github.com/openmina/openmina/blob/develop/mina-p2p-messages/src/v2/hashing.rs#L801)
- [ ] `gossip_v2`
- [ ] `decode_alloc_check_inputs`
- [ ] `jsonify_gossip_v2_roundtrip`
- [ ] ~~`test_bare_base58btc_pk`, see https://github.com/o1-labs/mina-rust/issues/1602~~
- [ ] `test_verify_zkapp`, see https://github.com/o1-labs/mina-rust/issues/1614

# Empty tests/Commented out:

- [ ] `test_make_verifier_index`, see https://github.com/o1-labs/mina-rust/issues/1601
- [ ] [binprot-read.rs](https://github.com/openmina/openmina/blob/develop/mina-p2p-messages/tests/binprot-read.rs)
- [x] ~~[`incoming_rpc_one_by_one`](https://github.com/openmina/openmina/blob/develop/mina-p2p-messages/tests/decode_bench.rs#38)~~
- [ ] [`test_tx_hash`](https://github.com/openmina/openmina/blob/develop/mina-p2p-messages/src/v2/hashing.rs#274)
- [ ] [`test_legacy_db`](https://github.com/openmina/openmina/blob/develop/ledger/src/database/database.rs#311)
- [ ] [`test_root_hash_v2`](https://github.com/openmina/openmina/blob/develop/ledger/src/database/database.rs#598)
- [ ] [`test_root_hash_legacy`](https://github.com/openmina/openmina/blob/develop/ledger/src/database/database.rs#666)
- [ ] [`test_derive_plonk`](https://github.com/openmina/openmina/blob/develop/ledger/src/proofs/public_input/plonk_checks.rs#926)
- [ ] [`snark_work`](https://github.com/openmina/openmina/blob/develop/ledger/src/scan_state/snark_work.rs#114)

## VRF/Consensus

- [x] `test_slot_calculation_time_big_producer`, see https://github.com/o1-labs/mina-rust/issues/1605
- [x] `test_first_winning_slot`, see https://github.com/o1-labs/mina-rust/issues/1606
- [x] `test_threshold_nonzero`, see https://github.com/o1-labs/mina-rust/issues/1607
- [x] `test_threshold_increase`, see https://github.com/o1-labs/mina-rust/issues/1608

## RPC

- [ ] `block`, see https://github.com/o1-labs/mina-rust/issues/1603
- [ ] `staged_ledger_aux_and_pending_coinbases_at_block`, see https://github.com/o1-labs/mina-rust/issues/1604

## Networking layer

- [x] `mutual_rust_to_libp2p_port_reuse`, see https://github.com/o1-labs/mina-rust/issues/399.

# Flaky tests

## Networking layer

- [x] [`mutual_rust_to_rust_many`](https://github.com/openmina/openmina/blob/main/p2p/tests/connection.rs)
  - Fixed by https://github.com/openmina/openmina/pull/569
- [ ] `mutual_rust_to_libp2p`, see https://github.com/o1-labs/mina-rust/issues/1600
- [ ] `p2p-scenario-tests: p2p_pubsub`, see https://github.com/o1-labs/mina-rust/issues/1448
- [ ] `record_replay_block_production`, see https://github.com/o1-labs/mina-rust/issues/1347
- [ ] `network::kad::p2p_network_kad_internals::tests::test_find_node_zero`, see https://github.com/o1-labs/mina-rust/issues/1332
- [x]  `rust_as_seed`, see https://github.com/o1-labs/mina-rust/issues/1300
- [x] `bootstrap_from_replayer`, see https://github.com/o1-labs/mina-rust/issues/1591

**Comment by 0xMimir** [comment]
[PR](https://github.com/openmina/openmina/pull/569) with fix for `mutual_rust_to_rust_many`

[PR](https://github.com/openmina/openmina/pull/578) with fixes for `rust_to_ocaml`, `ocaml_to_rust`, `rust_to_ocaml_via_seed`, `ocaml_to_rust_via_seed`, `rust_as_seed`, rewrite of `kademlia_bootstrap`, and removal of `incoming_find_node`

**Comment by 0xMimir** [comment]
[PR](https://github.com/openmina/openmina/pull/592) with fix for `run_ocaml`

**Comment by 0xMimir** [comment]
Fixed `bootstrap_from_replayer`, [PR](https://github.com/o1-labs/mina-rust/issues/1591)

**Comment by 0xMimir** [comment]
Removed ignore on following tests:
* `test_convert_requests`
* `test_read_requests`
* `test_slot_calculation_time_big_producer`
* `test_first_winning_slot`
* `test_threshold_nonzero`
* `test_threshold_increase`
* `make_rsa_key`

Removed following tests:
* `incoming_rpc_one_by_one`
* `debugger_to_wire`
* `test_vrf`
* `test_bare_base58btc_pk`
* `sync_root_snarked_ledger`

Fixed tests:
* `initial_joining`
* `binable_base58check`
* `mutual_rust_to_libp2p_port_reuse`

[PR](https://github.com/o1-labs/mina-rust/pull/1682)

**Comment by richardpringle** [comment]
Closing #1551 and moving remaining work here.

The following crates still need to be enabled in the `unit-tests` CI job (currently excluded). We should create sub-tasks to enable them one by one (or in groups):

- [ ] mina-core (`core`)
- [ ] mina-macros (`macros`)
- [ ] snark
- [ ] p2p-testing (`p2p/testing`)
- [ ] libp2p-rpc-behaviour (`p2p/libp2p-rpc-behaviour`)
- [ ] node
- [ ] mina-node-common (`node/common`)
- [ ] mina-node-web (`node/web`)
- [ ] mina-node-invariants (`node/invariants`)
- [ ] replay_dynamic_effects (`cli/replay_dynamic_effects`)
- [ ] poseidon
- [ ] mina-transport (`tools/transport`)
- [ ] mina-bootstrap-sandbox (`tools/bootstrap-sandbox`)
- [ ] mina-gossipsub-sandbox (`tools/gossipsub-sandbox`)
- [ ] hash-tool (`tools/hash-tool`)
- [ ] ledger-tool (`tools/ledger-tool`)
- [ ] salsa-simple (`vendor/salsa-simple`)
- [ ] transaction_fuzzer (`tools/fuzzing`)
- [ ] mina-archive-breadcrumb-compare (`tools/archive-breadcrumb-compare`)
- [ ] webrtc-sniffer (`tools/webrtc-sniffer`)
- [ ] mina-fuzzer (`fuzzer`)

**Comment by richardpringle** [comment]
I have created the following sub-tasks to track the enabling of unit tests for the remaining crates:

- [ ] #1709 (mina-fuzzer)
- [ ] #1710 (mina-core)
- [ ] #1711 (mina-macros)
- [ ] #1712 (snark)
- [ ] #1713 (p2p-testing)
- [ ] #1714 (libp2p-rpc-behaviour)
- [ ] #1715 (node)
- [ ] #1716 (mina-node-common)
- [ ] #1717 (mina-node-web)
- [ ] #1718 (mina-node-invariants)
- [ ] #1719 (replay_dynamic_effects)
- [ ] #1720 (poseidon)
- [ ] #1721 (mina-transport)
- [ ] #1722 (mina-bootstrap-sandbox)
- [ ] #1723 (mina-gossipsub-sandbox)
- [ ] #1724 (hash-tool)
- [ ] #1725 (ledger-tool)
- [ ] #1726 (salsa-simple)
- [ ] #1727 (transaction_fuzzer)
- [ ] #1728 (mina-archive-breadcrumb-compare)
- [ ] #1729 (webrtc-sniffer)

We can now proceed to address these individually.
